- name: Deploy on AWS
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Deploy an instance
      os_server:
        state: present
        name: lamp01
        image: RHEL 8.0
        key_name: MY_SSH_KEY
        wait: yes
        flavor: t2.micro
        network: public
        Arch: HVM64
	AWSRegion: ap-southeast-1

- name: install apache & php
  remote_user: root
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "Install apache"
      package: name=apache state=present
    - name: "Install apache-php5"
      package: name=libapache-mod-php state=present
    - name: "Install php-cli"
      package: name=php-cli state=present
    - name: "Install php-mcrypt"
      package: name=php-mcrypt state=present
    - name: "Install php-gd"
      package: name=php-gd state=present


- name: Install MySQL
  user: root
  hosts: all
  become: True
  become_user: root
  vars:
    MySQL_root_pass: ReplaceWithYourPassword
  tasks:
    - name: Set MySQL root password
      debconf: name="mysql-server" question="mysql-server/root_password" value="{{MySQL_root_pass | quote}}" vtype="password"
    - name: Confirm MySQL root password
      debconf: name="mysql-server" question="mysql-server/root_password_again" value="{{MySQL_root_pass | quote}}" vtype="password"
    - name: test1
      apt: package={{ item }} state=present force=yes update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"
      with_items:
        - mysql-server
        - mysql-client
        - php 5.5
    - name: Create MySQL user
      mysql_user: user="Wiki" state="present" login_password="{{ ThisPasswordShouldBeChanged }}" login_user=root
    - name: Secures the MySQL root user
      mysql_user: user="root" password="{{ MySQL_root_pass }}" host="{{ item }}" login_password="{{MySQL_root_pass}}" login_user=root
      with_items:
        - 127.0.0.1
        - localhost
        - ::1
        - "{{ ansible_fqdn }}"
    - name: Removes the MySQL test database
      mysql_db: db=Wikidatabase state=present login_password="{{ MySQL_root_pass }}" login_user=root 

-Name: Configure Wiki
    - Install:
    - hosts: all
    - Stat: present
    - roles: 
        mediawiki
    - file:
       /var/www/mediawiki

services:
   sysvinit:
     mysqld:
       enabled: 'true'
       ensureRunning: 'true'
     httpd:
       enabled: 'true'
       ensureRunning: 'true'


WebServerSecurityGroup:
   Type: 'AWS::EC2::SecurityGroup'
     Properties:
       GroupDescription: Enable HTTP access via port 80
       SecurityGroupIngress:
         - IpProtocol: tcp
           FromPort: '80'
           ToPort: '80'
           CidrIp: 0.0.0.0/0
         - IpProtocol: tcp
           FromPort: '443'
           ToPort: '443'
           CidrIp: 0.0.0.0/0
	 - IpProtocol: tcp
           FromPort: '443'
           ToPort: '443'
           CidrIP: 0.0.0.0/0
